import { ArrowUpRight, ContactRound, Database, FileAudio, Globe2, Mic2, ShieldCheck } from "lucide-react";
import { PipelineNav } from "../components/PipelineNav";

const publicSources=[
  {type:"Podcast transcript",icon:<Mic2/>,title:"Scaling Operations at ElevenLabs",publisher:"Work in Progress · Startup Insider",url:"https://www.startbase.de/mediathek/startup-insider/scaling-operations-at-elevenlabs-work-i-16cfe976b6/",raw:"Career journey from astrophysics to leading operations in a high-growth company.",pull:"Career arc → astrophysics becomes a safe visual motif",confidence:"0.91"},
  {type:"First-person post",icon:<ContactRound/>,title:"The best ops teams go unnoticed",publisher:"Victoria Weller · LinkedIn",url:"https://www.linkedin.com/posts/victoriaaaaa_the-best-ops-teams-work-hard-to-go-unnoticedbecause-activity-7291086532864626688-cx22",raw:"The best ops teams work hard to go unnoticed—because when everything works, no one asks how.",pull:"Operating philosophy → central game metaphor",confidence:"0.97"},
  {type:"Interview transcript",icon:<FileAudio/>,title:"The rainy London bus insight",publisher:"Strange Ventures",url:"https://www.linkedin.com/posts/strangevc_we-had-a-great-chat-with-victoria-weller-activity-7108144822598733824-E5sy",raw:"Every single station is announced by a voice.",pull:"Personal story → opening scene and audio cue",confidence:"0.93"},
  {type:"Official company",icon:<Globe2/>,title:"People Operations vacancy",publisher:"ElevenLabs Careers",url:"https://www.linkedin.com/jobs/view/people-operations-at-elevenlabs-4423015338",raw:"Benefit administration, policy updates, HiBob, Deel and employee experience.",pull:"Problem evidence → benefits operations is in remit",confidence:"0.98"},
];
const crm=[
  {t:"00:49",speaker:"Saoirse Byrne",text:"We lost a senior research engineer… the reason was the package — not base, the package."},
  {t:"01:37",speaker:"Saoirse Byrne",text:"Health cover that includes family, dental, and something that makes the pension feel real."},
  {t:"04:28",speaker:"Saoirse Byrne",text:"That mailbox is genuinely two days a month of my life."},
];

export default function Sources(){return <main className="detailPage"><header className="detailHeader"><div className="brand"><span>y</span>yonder</div><PipelineNav/><div className="recordBadge"><i/> EVIDENCE RUN #EL-041</div></header><div className="detailWrap"><div className="pageLead"><div><small>01 · SOURCE INGESTION</small><h1>Show the receipts.</h1><p>Every fact stays attached to its origin. The audience can inspect raw text before seeing what the agent concludes.</p></div><div className="runMeta"><span>Target</span><b>ElevenLabs</b><span>Candidate</span><b>Victoria Weller</b></div></div>
  <section className="tierBlock"><div className="tierHeading"><div className="tierIcon purple"><Database/></div><div><small>TIER ONE</small><h2>First-party intelligence</h2><p>Information the selling team already owns: calls, notes, product activity and CRM history.</p></div><span className="truthBadge"><ShieldCheck/> PRIVATE · HIGHEST RELEVANCE</span></div><div className="sourceExplain"><b>Demo CRM call transcript</b><span>Seeded hackathon record from the cloned GTM repo · source: <code>elevenlabs-second-call.ts</code></span><em>Clearly labelled demo data—not represented as a real ElevenLabs call.</em></div><div className="transcriptBox"><div className="transcriptTop"><FileAudio/> Kota ↔ ElevenLabs · second call <span>24:00 · manual transcript</span></div>{crm.map(x=><div className="utterance" key={x.t}><time>{x.t}</time><b>{x.speaker}</b><p>{x.text}</p><button>Extracted signal <ArrowUpRight/></button></div>)}</div></section>
  <section className="tierBlock"><div className="tierHeading"><div className="tierIcon lime"><Globe2/></div><div><small>TIER TWO</small><h2>Third-party intelligence</h2><p>Public, attributable evidence about the company, the buyer and the competitive moment.</p></div><span className="truthBadge"><ShieldCheck/> PUBLIC · CITED</span></div><div className="providerRow"><div><b>Aviato</b><p>Structured people and company graph used to resolve identity, current employment and firmographics.</p></div><div><b>Open web</b><p>Official careers pages, prospect-authored posts, interviews, podcasts and timestamped transcripts.</p></div><div><b>Unify</b><p>Intent and orchestration layer—used to decide when an account enters the research workflow.</p></div></div><div className="publicSources">{publicSources.map(s=><article key={s.title}><div className="sourceCardHead"><span>{s.icon}</span><div><small>{s.type}</small><b>{s.title}</b><em>{s.publisher}</em></div><a href={s.url} target="_blank" rel="noreferrer"><ArrowUpRight/></a></div><div className="rawQuote"><label>RAW EVIDENCE</label><p>“{s.raw}”</p></div><div className="agentPull"><label>AGENT EXTRACTS</label><p>{s.pull}</p><span>{s.confidence} confidence</span></div></article>)}</div></section>
  <div className="nextStep"><div><small>NEXT</small><b>Watch raw evidence become structured claims</b></div><a href="/transform">Open transformation <ArrowUpRight/></a></div>
 </div></main>}
