import { Deal } from "./types";

export const deals: Deal[] = [
  {
    id: "northwind",
    company: "Northwind Freight",
    domain: "northwindfreight.com",
    industry: "Logistics & fleet management",
    headcount: 340,
    stage: "Sales Qualified Lead",
    value: 42000,
    closeDate: "2026-09-30",
    source: "Outbound",
    buyer: {
      name: "Dana Okoye",
      title: "VP Operations",
      seniority: "VP",
      tenure: "12y tenure, promoted twice internally",
      linkedin: "linkedin.com/in/danaokoye",
    },
    context: {
      incumbent: "FleetPilot TMS",
      timeline: "Renewal in Q3",
      budgetSignal: "Mentioned, unconfirmed",
      stakeholders: 2,
      competitors: ["FleetPilot", "Samsara", "Motive"],
    },
    quotes: [
      {
        text: "We're re-keying the same dispatch data into three systems every morning before anyone's had coffee.",
        call: 1,
        timestamp: "14:22",
        transcriptHref: "#",
      },
      {
        text: "I don't need another dashboard. I need the thing I'm already looking at to be right.",
        call: 1,
        timestamp: "21:05",
        transcriptHref: "#",
      },
    ],
    conflicts: [
      {
        field: "Headcount",
        values: [
          { value: "about 300", source: "Call 1 transcript" },
          { value: "340", source: "LinkedIn enrichment" },
        ],
      },
    ],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Ready — sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "waiting", detail: "Generates after Call 2" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "2h ago",
    callsCompleted: 1,
  },
  {
    id: "fernhill",
    company: "Fernhill Clinics",
    domain: "fernhillclinics.co",
    industry: "Healthcare",
    headcount: 210,
    stage: "Meeting Booked",
    value: 19500,
    closeDate: "2026-10-15",
    source: "Referral",
    buyer: {
      name: "R. Adeyemi",
      title: "Head of IT",
      seniority: "Head of",
      tenure: "4y tenure",
      linkedin: "linkedin.com/in/radeyemi",
    },
    context: {
      incumbent: "Manual spreadsheets",
      timeline: "No pressing deadline",
      budgetSignal: "Not yet discussed",
      stakeholders: 1,
      competitors: ["Compliance365"],
    },
    quotes: [
      {
        text: "Anything that keeps us audit-ready without a rep chasing me for updates is a win.",
        call: 1,
        timestamp: "08:40",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "waiting", detail: "Generates after Call 1" },
      { name: "Collateral pack", kind: "collateral", status: "waiting", detail: "Generates after Call 2" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "yesterday",
    callsCompleted: 0,
  },
  {
    id: "basalt",
    company: "Basalt Robotics",
    domain: "basaltrobotics.io",
    industry: "Industrial robotics",
    headcount: 610,
    stage: "Sales Qualified Lead",
    value: 66500,
    closeDate: "2026-09-20",
    source: "Inbound",
    buyer: {
      name: "T. Lindqvist",
      title: "CTO",
      seniority: "C-suite",
      tenure: "6y tenure, founding engineer",
      linkedin: "linkedin.com/in/tlindqvist",
    },
    context: {
      incumbent: "Gong",
      timeline: "Evaluating through Q4",
      budgetSignal: "Budget approved",
      stakeholders: 3,
      competitors: ["Gong", "Chorus"],
    },
    quotes: [
      {
        text: "We already pay for call intelligence. What we don't have is anyone acting on it between calls.",
        call: 1,
        timestamp: "05:12",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Ready — sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "waiting", detail: "Generates after Call 2" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "3d ago",
    callsCompleted: 1,
  },
  {
    id: "harrow",
    company: "Harrow & Vale",
    domain: "harrowandvale.com",
    industry: "Professional services",
    headcount: 480,
    stage: "Sales Qualified Opportunity",
    value: 58000,
    closeDate: "2026-09-05",
    source: "Outbound",
    buyer: {
      name: "S. Marsh",
      title: "Sales Director",
      seniority: "Director",
      tenure: "3y tenure",
      linkedin: "linkedin.com/in/smarsh",
    },
    context: {
      incumbent: "Homegrown spreadsheet CRM",
      timeline: "Wants to close before fiscal year end",
      budgetSignal: "Budget confirmed",
      stakeholders: 3,
      competitors: ["Salesloft", "Outreach"],
    },
    quotes: [
      {
        text: "Every rep writes the recap differently. New hires can't tell what actually happened on a call.",
        call: 2,
        timestamp: "11:03",
        transcriptHref: "#",
      },
      {
        text: "If it can't prove where a fact came from, my team won't trust it.",
        call: 2,
        timestamp: "19:47",
        transcriptHref: "#",
      },
    ],
    conflicts: [
      {
        field: "Decision timeline",
        values: [
          { value: "\"by end of quarter\"", source: "Call 1 transcript" },
          { value: "\"no fixed date yet\"", source: "Call 2 transcript" },
        ],
      },
    ],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "waiting", detail: "Generating…" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "1h ago",
    callsCompleted: 2,
  },
  {
    id: "coppervale",
    company: "Coppervale Media",
    domain: "coppervale.media",
    industry: "Advertising",
    headcount: 145,
    stage: "Proposal",
    value: 36000,
    closeDate: "2026-08-28",
    source: "Referral",
    buyer: {
      name: "J. Kowalski",
      title: "Head of RevOps",
      seniority: "Head of",
      tenure: "2y tenure",
      linkedin: "linkedin.com/in/jkowalski",
    },
    context: {
      incumbent: "None — first CRM buildout",
      timeline: "Live by next quarter",
      budgetSignal: "Budget confirmed",
      stakeholders: 2,
      competitors: ["HubSpot", "Attio"],
    },
    quotes: [
      {
        text: "I'd rather ship something that's 80% right today than wait for the perfect system in six months.",
        call: 2,
        timestamp: "09:18",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "sent", detail: "Published — sent after Call 2", href: "#" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "5h ago",
    callsCompleted: 2,
  },
  {
    id: "aldergate",
    company: "Aldergate Health",
    domain: "aldergatehealth.org",
    industry: "Healthcare networks",
    headcount: 920,
    stage: "Decision Maker Bought-In",
    value: 81000,
    closeDate: "2026-08-22",
    source: "Outbound",
    buyer: {
      name: "M. Osei",
      title: "COO",
      seniority: "C-suite",
      tenure: "9y tenure",
      linkedin: "linkedin.com/in/mosei",
    },
    context: {
      incumbent: "Manual CRM entry, no enrichment",
      timeline: "Signing this month",
      budgetSignal: "Commercials confirmed",
      stakeholders: 4,
      competitors: ["Gong", "Clari"],
    },
    quotes: [
      {
        text: "Show my board this replaces three people's Friday afternoons and it sells itself.",
        call: 3,
        timestamp: "16:02",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "sent", detail: "Sent after Call 2", href: "#" },
      { name: "Contract", kind: "contract", status: "sent", detail: "Generating — commercials confirmed", href: "#" },
    ],
    lastActivity: "2d ago",
    callsCompleted: 3,
  },
  {
    id: "kroobank",
    company: "Kroo Bank",
    domain: "kroobank.com",
    industry: "Fintech",
    headcount: 250,
    stage: "Sales Qualified Opportunity",
    value: 48000,
    closeDate: "2026-09-12",
    source: "Inbound",
    buyer: {
      name: "D. Adcock",
      title: "Head of Growth",
      seniority: "Head of",
      tenure: "5y tenure",
      linkedin: "linkedin.com/in/dadcock",
    },
    context: {
      incumbent: "Pipedrive",
      timeline: "Q4 rollout",
      budgetSignal: "Estimating range",
      stakeholders: 2,
      competitors: ["Pipedrive", "Close"],
    },
    quotes: [
      {
        text: "Pipedrive's fine for tracking deals. It's useless for telling me what actually got said.",
        call: 2,
        timestamp: "12:40",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "waiting", detail: "Generating…" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "3d ago",
    callsCompleted: 2,
  },
  {
    id: "lumin",
    company: "Lumin Nuclear Medicine",
    domain: "luminnm.com",
    industry: "Medical imaging",
    headcount: 88,
    stage: "Proposal",
    value: 1440,
    closeDate: "2026-09-01",
    source: "Inbound",
    buyer: {
      name: "S. Vance",
      title: "Ops Lead",
      seniority: "Lead",
      tenure: "1y tenure",
      linkedin: "linkedin.com/in/svance",
    },
    context: {
      incumbent: "None",
      timeline: "Piloting on a small team first",
      budgetSignal: "Small trial budget",
      stakeholders: 1,
      competitors: [],
    },
    quotes: [
      {
        text: "We're tiny. If setup takes longer than a call, we won't finish it.",
        call: 2,
        timestamp: "10:11",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "sent", detail: "Published — sent after Call 2", href: "#" },
      { name: "Contract", kind: "contract", status: "waiting", detail: "Generates after Call 3" },
    ],
    lastActivity: "2 days ago",
    callsCompleted: 2,
  },
  {
    id: "digi2al",
    company: "Digi2al",
    domain: "digi2al.com",
    industry: "eCommerce tooling",
    headcount: 50,
    stage: "Decision Maker Bought-In",
    value: 9600,
    closeDate: "2026-08-30",
    source: "Outbound",
    buyer: {
      name: "P. Nkemdirim",
      title: "Founder",
      seniority: "C-suite",
      tenure: "Founder, 3y",
      linkedin: "linkedin.com/in/pnkemdirim",
    },
    context: {
      incumbent: "Notion + spreadsheets",
      timeline: "Ready now",
      budgetSignal: "Commercials confirmed",
      stakeholders: 1,
      competitors: ["Notion"],
    },
    quotes: [
      {
        text: "As a founder I'm the whole RevOps team. I need this to run itself.",
        call: 3,
        timestamp: "13:55",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "sent", detail: "Sent after Call 2", href: "#" },
      { name: "Contract", kind: "contract", status: "sent", detail: "Generating — commercials confirmed", href: "#" },
    ],
    lastActivity: "19 days ago",
    callsCompleted: 3,
  },
  {
    id: "shinka",
    company: "Shinka",
    domain: "shinka.io",
    industry: "Developer tools",
    headcount: 34,
    stage: "Closed Won",
    value: 12000,
    closeDate: "2026-08-10",
    source: "Inbound",
    buyer: {
      name: "Y. Tanaka",
      title: "Engineering Manager",
      seniority: "Manager",
      tenure: "2y tenure",
      linkedin: "linkedin.com/in/ytanaka",
    },
    context: {
      incumbent: "Linear notes",
      timeline: "Closed",
      budgetSignal: "Paid",
      stakeholders: 2,
      competitors: [],
    },
    quotes: [
      {
        text: "The game was the reason I forwarded the email to the rest of the team.",
        call: 3,
        timestamp: "17:30",
        transcriptHref: "#",
      },
    ],
    conflicts: [],
    artefacts: [
      { name: "Personalised game", kind: "game", status: "sent", detail: "Sent after Call 1", href: "#" },
      { name: "Collateral pack", kind: "collateral", status: "sent", detail: "Sent after Call 2", href: "#" },
      { name: "Contract", kind: "contract", status: "sent", detail: "Signed", href: "#" },
    ],
    lastActivity: "5 days ago",
    callsCompleted: 3,
  },
];

export function dealsByStage(stage: string) {
  return deals.filter((d) => d.stage === stage);
}

export function stageTotal(stage: string) {
  return dealsByStage(stage).reduce((sum, d) => sum + d.value, 0);
}
